name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Vader tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: better-code-block

      - name: Install Vim
        run: |
          sudo apt-get update
          sudo apt-get install -y vim

      - name: Clone Vader
        run: |
          git clone https://github.com/junegunn/vader.vim.git

      - name: Run tests
        run: |
          cd better-code-block
          chmod +x run_tests.sh
          # Use timeout in CI environment to prevent hung tests
          timeout 60s ./run_tests.sh
